#define CONFIG_AR7240 1
#define CONFIG_MACH_HORNET 1
#define CONFIG_HORNET_1_1_WAR 1
#define NEW_DDR_TAP_CAL 1
#define FLASH_SIZE 4
#define GPIO_RST_BUTTON_BIT		12
#define CONFIG_DELAY_TO_AUTORUN_HTTPD		2
#define CONFIG_DELAY_TO_AUTORUN_UPGRADE		8
#define CONFIG_DELAY_TO_AUTORUN_CONSOLE	15
#define CONFIG_MAX_BUTTON_PRESSING 20

/* Automatically generated - do not edit */
#include <configs/ap121.h>
